### ISSUE TITLE
The first issue, When the source opened?

### ISSUE THREAD

**Issue by ForestWang** [embodied-generalist/embodied-generalist#1]

**Comment by Asianfleet** [comment]
same question. it's an awesome project and I' m crossing my finger

**Comment by huangjy-pku** [comment]
Thanks for your interest in our project! We are re-organizing the code and hope to release soon.

**Comment by gunny97** [comment]
Thank you for your awesome work!
Are you also planning to release the training data used in LEO?

**Comment by huangjy-pku** [comment]
> Thank you for your awesome work! Are you also planning to release the training data used in LEO?

Yes, it is also in the plan.

**Comment by Hoyyyaard** [comment]
Thank you for your awesome work!
May I ask if you can share the approximate time for the code and data to be open-sourced?

**Comment by huangjy-pku** [comment]
Hello, sorry for being late. We have just released our code and data. Welcome to explore and use. If you have any questions, don't hesitate to reach out :)
