### ISSUE TITLE
timm.create_model error

### ISSUE THREAD

**Issue by lidingzhe** [embodied-generalist/embodied-generalist#15]
hi~, when I run the inference.py.
 I find 
`m = timm.create_model('convnext_base.clip_laion2b', pretrained=True)` 
is right, but
 `m = timm.create_model('convnext_base.clip_laion2b', pretrained=False) 
state_dict = torch.load('/home/usr/.cache/huggingface/hub/models--laion--CLIP-convnext_base_w-laion2B-s13B-b82K/snapshots/43cc4adea32de0ca94f71bfe1162eba29c824d6e/open_clip_pytorch_model.bin') m.load_state_dict(state_dict)` is wrong. 
I make show the state_dict and reset the state_dict to delet visual.trunk. but I find there is missing the head.fc.weight and head.fc.bias.
what I should do to make loading checkpoint offline.
Look forward to your response. Thank you.

**Comment by lidingzhe** [comment]
m.load_state_dict(state_dict, strict=False)？ is right？

**Comment by huangjy-pku** [comment]
Yes. It should work with `strict=False`. However, be careful of the `state_dict` keys when loading in this way.

**Comment by lidingzhe** [comment]
Thanks to your response.  `strict=False`  can run, but it will impact the model's performance. I find `timm/models/convnext.py` have the` checkpoint_filter_fn(state_dict)`. When using this function to filter the state_dict, the `inference.py ` can run. Express my gratitude to you once again.

**Comment by lidingzhe** [comment]
when you copy the `.cache/huggingface/hub` to other computer and using timm('', pretrained=True). to revise ` /home/usr/miniforge3/envs/leo/lib/python3.9/site-packages/huggingface_hub/file_download.py`  `revision = 'd94f3f016ae679c3008de268209132f2d93b3d2b'` and make sure your ` /home/usr/.cache/huggingface/hub/models--laion--CLIP-convnext_base_w-laion2B-s13B-b82K/snapshots/TBD/open_clip_pytorch_model.bin` TBD is d94f3f016ae679c3008de268209132f2d93b3d2b.

**Comment by huangjy-pku** [comment]
So, is there any problem that I can help with? Why don't you just use `pretrained=True`? The issues you raised seem more related to the `timm` package.

**Comment by lidingzhe** [comment]
Yes, setting `pretrined=True` is indeed the right approach. If the computer cannot connect to the Hugging Face website, I need to download the files manually and specify the path. I would like to add some issues regarding manual downloads. Thank you very much for your reply and your previous help. Regarding LEO, I will need to trouble you and seek your guidance in the future.  Express my gratitude to you once again.

**Comment by huangjy-pku** [comment]
I see. By the way, if you just want to run VL tasks with EAI tasks excluded, you do not bother to handle the issues of 2D encoder since it is not used in 3D VL tasks.

**Comment by lidingzhe** [comment]
Thank you for your reply. I'll study the code some more.

**Comment by TesiLin** [comment]
I managed to load the checkpoint offline. In case someone encounters this issue later, here's my solution.

In file `LEO/model/vision2d.py`, edit function `convnext_base_laion2b()` as below:
```
m = timm.create_model(
        'convnext_base.clip_laion2b',
        pretrained=pretrained,
        pretrained_cfg_overlay=dict(file="local_pretrained_weights_folder/CLIP-convnext_base_w-laion2B-s13B-b82K-augreg/open_clip_pytorch_model.bin")
    )
```

There's no need to manually set the state_dict or cache file route. I don't know if this will solve the issue.
