### ISSUE TITLE
Question about 3D point cloud feature extraction

### ISSUE THREAD

**Issue by LYX0501** [embodied-generalist/embodied-generalist#16]
Hello Jiangyong, 

Thanks for your work LEO. Its object-centric 3D representation impresses me deeply. 

When I try to extract object point cloud by Mask3D as your paper described, I find Mask3D's performance is not very convincing (missing / wrong predictions). I use the "scannet200_benchmark.ckpt" as Mask3D checkpoint and set the confidence_threshold to 0.7. 

However, I further test Mask3D web demo (https://francisengelmann.github.io/mask3d/) . Its performance is extremely good. 

Therefore, I am wondering how you extract object-centric 3D representation by Mask3D. Can you achieve the same performance as their web demo?

**Comment by huangjy-pku** [comment]
Resolved in personal communication. The performance of running script is comparable to web demo when using the right script (`scannet200_val.sh`).
