### ISSUE TITLE
inference result not correct?

### ISSUE THREAD

**Issue by jianzfb** [embodied-generalist/embodied-generalist#17]
Dear author,
    I run your code, but I get a not correct result. The snapshot is like this, 
<img width="1247" alt="image" src="https://github.com/embodied-generalist/embodied-generalist/assets/16849192/bcee7c0d-cfe6-4e60-afbb-56a222649ab7">
   I don't know what happens. It seems that all pretrained models have been loaded successfully.
   Look forward to your response. Thank you.

**Comment by huangjy-pku** [comment]
Our `Vicuna` is based on version `v1.1` (see [model weights](https://github.com/embodied-generalist/embodied-generalist#model-weights))

**Comment by jianzfb** [comment]
Thank you. It works.
