### ISSUE TITLE
Loss NaN during lora tuning

### ISSUE THREAD

**Issue by CurryYuan** [embodied-generalist/embodied-generalist#18]
Thanks for your interesting work.

I encounter Nan loss at the first few steps during the training with the provided scripts `scripts/train_align_lora.sh`. Things goes well when using `scripts/train_align_frozen.sh`. Any ideas?

**Comment by huangjy-pku** [comment]
Chances are that the training of LLM goes unstable, especially when tuning more parameters. You can try a different seed though the default seed has not caused `NaN` in my experiments.
