### ISSUE TITLE
求 EAI任务debug数据集

### ISSUE THREAD

**Issue by FanZhang91** [embodied-generalist/embodied-generalist#19]
您好。您在其他的issues说EAI任务(navigation和action)数据集很大，无法上传。能不能上传个debug版本的EAI数据集，有几个少量样本，方便大家调试和理解方法细节？

**Comment by huangjy-pku** [comment]
@jeasinema

**Comment by CurryYuan** [comment]
Any updates?

**Comment by huangjy-pku** [comment]
We have released a few data examples of EAI tasks. See the EAI part in [Task and data](https://github.com/embodied-generalist/embodied-generalist?tab=readme-ov-file#task-and-data).
