### ISSUE TITLE
Thank for your great work, and I have some question.

### ISSUE THREAD

**Issue by drilistbox** [embodied-generalist/embodied-generalist#2]
Thank for your great work, and I have some question：
1. when will the instruction-tuned LEO weights be released
2. how to implement various types of simulations (such as Robotic Manipulation, Embodied Navigation ) in the web page ( https://embodied-generalist.github.io/ )?

**Comment by huangjy-pku** [comment]
1. Within one week.
2. The implementation can be found in the repo for our github page.

**Comment by drilistbox** [comment]
Thanks for your quick reply. 
But I found the news that "[2024.03] We release the code and data. The embodied AI (EAI) tasks (navigation and manipulation) need further organization and will be released soon.", it seems that navigation and manipulation have not been released.

Besides, I found test_scannet_mask3d.sh in the folder of ./scripts. Directly run the shell with "bash scripts/test_scannet_mask3d", the program finished quickly as following screenshot:


I apologize for my ignorance, but how can I run the interactive demo or the demo shown on the huggingface(https://huggingface.co/spaces/embodied-generalist/LEO-Demo)?  

Thanks a lot!

**Comment by huangjy-pku** [comment]
Sorry for the misunderstanding. The navigation and manipulation tasks are under re-organization and it takes some time to release.

The shell scripts launch in `submitit` mode by default. Please check your hardware and choose a proper mode to run.

You can play the interactive demo on the webpage. But if you want to launch your own demo, I am sorry we cannot offer support.

**Comment by huangjy-pku** [comment]
Our work does not involve the control of a robot arm. We use [CLIPort](https://cliport.github.io/) for the manipulation task.

**Comment by drilistbox** [comment]
Thanks a lot!
