### ISSUE TITLE
how to execute the project

### ISSUE THREAD

**Issue by cuizhuzhuchen** [embodied-generalist/embodied-generalist#20]
The environment is set up, and the data is prepared. How should this project be executed?How to execute the project to generate a checkpoint? Could you provide a detailed step-by-step guide?Execute the command `bash scripts/train_align_lora.sh`, but there is no response.Executing other .sh files under the scripts directory also does not result in any changes.
![image](https://github.com/embodied-generalist/embodied-generalist/assets/148684034/0eda9717-5481-4629-a181-2bca3d3ab3d9)
8 NVIDIA RTX 4090 24GB graphics cards.

**Comment by huangjy-pku** [comment]
You need to figure out the type of your server first. If it is based on `SLURM`, you can launch jobs via `mode=submitit`, which is the default option. If it is not, you can launch jobs via `mode=accelerate` for distributed training. The option `mode=python` only supports single-GPU running.
