### ISSUE TITLE
How to Use Multi-GPU Training

### ISSUE THREAD

**Issue by TimXXX123** [embodied-generalist/embodied-generalist#23]
How to Use Multi-GPU Training  (4*3090)

**Comment by huangjy-pku** [comment]
You need to figure out the type of your server first. If it is based on `SLURM`, you can launch jobs via `mode=submitit`, which is the default option. If it is not, you can launch jobs via `mode=accelerate` for distributed training. For explanation of the launch arguments, use `python launch.py --help`. Refer to [SLURM submitit](https://github.com/facebookincubator/submitit) or [Accelerate](https://huggingface.co/docs/accelerate/index) for more information.
