### ISSUE TITLE
How can we use other data to inference

### ISSUE THREAD

**Issue by neufengyun** [embodied-generalist/embodied-generalist#26]
Thanks for your great job first, but I have a question, how can I use my own RGB-D data to do inference, what steps I should follow?

**Comment by huangjy-pku** [comment]
You can scatter the RGB-D pixels to 3D space to get (surface) points and then obtain the meshes. After that, you can sample from the meshes to get point clouds. Anyway, the model requires point cloud input with XYZRGB channels.
