### ISSUE TITLE
How to load trained LEO weights in inference process?

### ISSUE THREAD

**Issue by yu3jun** [embodied-generalist/embodied-generalist#31]
Hi, thanks for your excellent work,

In your doc, you said we can select a checkpoint by specifying either `note` or `pretrained_ckpt_path`. For the former, note should align with the corresponding note for the training exp_dir. For the latter, you shoud assign with a checkpoint folder wherein `pytorch_model.bin` exists.

However , if I run the inference.sh in:

`python launch.py --mode python \
                 --run_file inference.py \
                 --config configs/default.yaml \
                 note=tuning_noact \
                 pretrained_ckpt_path=null \`

It returns error like:
Error executing job with overrides: ['num_gpu=1', 'note=tuning_noact', 'pretrained_ckpt_path=null']
Traceback (most recent call last):
  File "/root/experiments/embodied-generalist/inference.py", line 191, in main
    prober = LeoProber(cfg)
  File "/root/experiments/embodied-generalist/inference.py", line 51, in __init__
    raise ValueError("No checkpoint to load for evaluation")
ValueError: No checkpoint to load for evaluation

However , if I run the inference.sh in:
`python launch.py --mode python \
                 --run_file inference.py \
                 --config configs/default.yaml \
                 note=tuning_noact \
                 pretrained_ckpt_path='/root/experiments/embodied-generalist/checkpoints/align.pth' \`

It returns:
Error executing job with overrides: ['num_gpu=1']
Traceback (most recent call last):
  File "/root/experiments/embodied-generalist/inference.py", line 191, in main
    prober = LeoProber(cfg)
  File "/root/experiments/embodied-generalist/inference.py", line 54, in __init__
    self.load(path=self.pretrained_ckpt_path, model_only=True)
  File "/root/experiments/embodied-generalist/trainer/leo_trainer.py", line 294, in load
    model_state_dict = torch.load(os.path.join(path, 'pytorch_model.bin'))
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/leo/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
NotADirectoryError: [Errno 20] Not a directory: '/root/experiments/embodied-generalist/checkpoints/align.pth/pytorch_model.bin'

**I'm still confused about how to load the trained weights, and where is the pytorch_model.bin ?**

**Comment by huangjy-pku** [comment]
I see. Seems some misunderstanding at loading checkpoint. When running inference, if there exists a folder aligned with the name of `note`, it will automatically load `${note}/best.pth/pytorch_model.bin`. If not, it will turn to load `${pretrained_ckpt_path}/pytorch_model.bin` if this path exists. To clarify, the pretrained model weights should be renamed to `pytorch_model.bin` and placed in the right path in order to be loaded.

**Comment by yu3jun** [comment]
Thanks for your quick answer, but I have few more questions.

1. You have released Trained LEO weights : `align.pth` and  `sft_noact.pth`. Do these two files are the pretrained model weights we need to place in the pretrained_ckpt_path?  And shall we rename them directly to` pytorch_model.bin`?

2. In the function `load_scene` in ` inference.py`, you used `self.load_rscan`, `self.load_scannet`, `self.preprocess_pcd`, but I couldn't find where are they defined.

3. If I want to generate a complete room scene caption rather than a single object, besides the `img_fts` and `obj_fts`, do the `img_masks`, `obj_tokens`,  `obj_masks` and `obj_locs` are also necessary in the data_dict?

Thank you very much !

**Comment by huangjy-pku** [comment]
1. Yes. Please refer to the loading convention in `trainer/leo_trainer.py`.
2. Please refer to the parent class.
3. Use the prompt for scene captioning. Please refer to `data/datasets.py` and `model/vision3d.py`.

**Comment by yu3jun** [comment]
> 1. Yes. Please refer to the loading convention in `trainer/leo_trainer.py`.
> 2. Please refer to the parent class.
> 3. Use the prompt for scene captioning. Please refer to `data/datasets.py` and `model/vision3d.py`.

Can you give an example about how to use the prompt for scene captioning to execute inference.sh? which file should we modify?

**Comment by CurryYuan** [comment]
Hi, @huangjy-pku ,
How to use ``pointbert_pointllm.pth`` weight? Do you have the corresponding LEO weight and config?

**Comment by huangjy-pku** [comment]
> @huangjy-pku Same questions as yu3jun. Is there any difference between pytorch_model.bin and the models you releases with *.pth?
> 
> I also run `sh script/inference.sh` and the script is as below.
> 
> ```
> python launch.py --mode python \
>                  --run_file inference.py \
>                  --config configs/default.yaml \
>                  --gpu_per_node 1 \
>                 #  note=tuning_noact \
>                 pretrained_ckpt_path='path_to_ckpt/pytorch_model.bin' \
> ```
> 
> the result is :
> 
> ```
> File "/home/sven/embodied-generalist/inference.py", line 191, in main
>     prober = LeoProber(cfg)
>   File "/home/sven/embodied-generalist/inference.py", line 51, in __init__
>     raise ValueError("No checkpoint to load for evaluation")
> ValueError: No checkpoint to load for evaluation
> [2024-07-11 18:19:59,296] - Launched
> ```
> 
> How to properly execute inference.sh?

Referring to [`LeoTrainer.load` function](https://github.com/embodied-generalist/embodied-generalist/blob/main/trainer/leo_trainer.py#L292), you can see the checkpoint structure is `{path_to_ckpt}/pytorch_model.bin`. `best.pth` is the folder name and `pytorch_model.bin` is the checkpoint name. So, you should rename the `*.pth` files to `pytorch_model.bin` and place it in a folder `{path_to_ckpt}`. Then specify the `path` argument to `{path_to_ckpt}` in `load` function. Sorry for the misleading, but a glance of the code would quickly address the confusion.

**Comment by huangjy-pku** [comment]
> > 1. Yes. Please refer to the loading convention in `trainer/leo_trainer.py`.
> > 2. Please refer to the parent class.
> > 3. Use the prompt for scene captioning. Please refer to `data/datasets.py` and `model/vision3d.py`.
> 
> Can you give an example about how to use the prompt for scene captioning to execute inference.sh? which file should we modify?

Please refer to [prompt loading](https://github.com/embodied-generalist/embodied-generalist/blob/main/inference.py#L60) and [prompt setting](https://github.com/embodied-generalist/embodied-generalist/blob/main/configs/default.yaml#L66).

**Comment by huangjy-pku** [comment]
> Hi, @huangjy-pku , How to use `pointbert_pointllm.pth` weight? Do you have the corresponding LEO weight and config?

Yes. See [weights](https://huggingface.co/datasets/huangjy-pku/LEO_data/tree/main) and [config](https://github.com/embodied-generalist/embodied-generalist/blob/main/configs/vision3d/backbone/pointbert.yaml).
