### ISSUE TITLE
Question for how to implement interactive demo

### ISSUE THREAD

**Issue by jkstyle2** [embodied-generalist/embodied-generalist#32]
Thanks for sharing your great work!

I'd like to test a customized dataset using your interactive demo.
I'm wondering if there is a sample code or project that you can share or I can refer to for implementing the interactive demo as yours.

Thanks for your reply in advance!

**Comment by huangjy-pku** [comment]
You can refer to [HuggingFace demo](https://huggingface.co/spaces/embodied-generalist/LEO-Demo/tree/main).

**Comment by jkstyle2** [comment]
@huangjy-pku 
Hello, I'm trying to test the LEO-Demo app, but there's a key error for 'LOG_ACCESS_TOKEN' as below.
Do you know how to solve it? 

```
~/embodied-generalist/LEO-Demo$ python app.py
.gitattributes: 100%|
README.md: 100%|
generation_config.json: 100%|
pytorch_model.bin.index.json: 100%|
special_tokens_map.json: 100%|
config.json: 100%|
tokenizer_config.json: 100%|
tokenizer.model: 100%|
pytorch_model-00002-of-00002.bin: 100%|
pytorch_model-00001-of-00002.bin: 100%|
Fetching 10 files: 100%|
Loading checkpoint shards: 100%|
leo_noact_hf.pth: 100%|
Traceback (most recent call last):
  File "~/embodied-generalist/LEO-Demo/app.py", line 5, in <module>
    from utils import *
  File "~/embodied-generalist/LEO-Demo/utils.py", line 51, in <module>
    access_token = os.environ['LOG_ACCESS_TOKEN']
  File "~/miniconda3/envs/groupfree/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOG_ACCESS_TOKEN'
```

**Comment by huangjy-pku** [comment]
This is a particular key that I need to launch the demo but have kept private. You can modify this or simply remove it according to your demand.
