### ISSUE TITLE
How to debug the code using debugpy in vscode

### ISSUE THREAD

**Issue by jkstyle2** [embodied-generalist/embodied-generalist#33]
Thanks for sharing your great work.

I'm trying to understand what's going on in your code, step-by-step.
I've created launch.json in vscode with debugpy type option instead of directly running inference.sh script.
I set breakpoints in a few lines in launch.py, launch_utils.py, inference.py.
However, the debugger works only in launch.py, launch_utils.py, and it just doesn't make any stop inside module after subprocess.run(cmd, shell=True) in launch_utils.py. 
Can you advise how to solve it or suggest any other debugging ways?

Thanks for your help in advance!

**Comment by Germany321** [comment]
You should add '--mode python' in the .sh file to trigger the debug mode, then you can use the debug tools like ipdb and ipython.

**Comment by jkstyle2** [comment]
@Germany321 
I just ran [inference.py](https://github.com/embodied-generalist/embodied-generalist/blob/main/scripts/inference.sh) which has already --mode python as an argument. It begins with debugging mode in launch.py, but it just cannot debug into [subprocess.run](https://github.com/embodied-generalist/embodied-generalist/blob/16cc857b4a3411b07d957d168d3ecd5bef2b71f3/common/launch_utils.py#L146C10-L146C35) in launch_utils.py. Is this issue only for myself?

**Comment by Germany321** [comment]
Did you run the code in a cluster or a native server?

**Comment by jkstyle2** [comment]
I use a single local PC with RTX 6000 Ada. I cannot debug into the internal modules after running subprocess().
Should I need to directly run inference.py without launch.py for a single server?

**Comment by Germany321** [comment]
Can you provide the detailed information of the error?

**Comment by jkstyle2** [comment]
I found it was an issue with subprocess that cannot track the debugger launched for main process.
It was solved with either inserting debugpy module into inference.py or calling the inference script directly as below to use only a single main process.


```
from inference import main as inference_main

def python_launch(args):
    """
    Vanilla python launcher for degbugging purposes
    """
    opts = " ".join(args.opts) if len(args.opts) > 0 else ""
    full_cfg_path = Path(args.config)
    cfg_path, cfg_file = str(full_cfg_path.parent), str(full_cfg_path.name)
    cmd = f"python {args.run_file} \
            --config-path {cfg_path} \
            --config-name {cfg_file} \
            num_gpu=1 \
            hydra.run.dir=. \
            hydra.output_subdir=null \
            ~hydra.job_logging.handlers.file \
            hydra.job_logging.root.handlers=[console] \
            hydra/hydra_logging=disabled {opts}"
        
    # subprocess.run(cmd, shell=True)

    # Set the sys.argv to mimic the command line arguments
    sys.argv = ['inference.py', 
                '--config-path', str(Path(args.config).parent),
                '--config-name', str(Path(args.config).name)]

    # Add additional arguments from opts
    if args.opts:
        sys.argv.extend(args.opts)

    inference_main()
```
