### ISSUE TITLE
About the dataset preprocess

### ISSUE THREAD

**Issue by yu3jun** [embodied-generalist/embodied-generalist#35]
Hi, 

Could you give some guidance about how to preprocess the 3RScan/Scannet datasets in your work?
And if possible, could you open source the preprocess code please?

Thank you very much!

**Comment by huangjy-pku** [comment]
If you mean the preprocess is about the transformation from raw mesh to axis-aligned point cloud, you can refer to issue #21 for more information. However, the specific code is not yet ready for release.

If you mean the data process from axis-aligned point cloud to the model input, you can check `data/datasets.py`.

**Comment by huangjy-pku** [comment]
Sorry for being late. Check details [here](https://github.com/scene-verse/SceneVerse/blob/main/preprocess/README.md).
