### ISSUE TITLE
复现LEO时scan2cap任务的相关问题

### ISSUE THREAD

**Issue by xjj1999** [embodied-generalist/embodied-generalist#38]
您好，我重复了两阶段训练，发现在第一阶段scan2cap验证集上，对于不同场景不同的问题输入，输出的回答总是相似的，请问作者在实验过程中有碰到这个现象吗？

**Comment by huangjy-pku** [comment]
这可能是overfit了object captioning data导致的

**Comment by xjj1999** [comment]
请问方便提供scan2cap的评测指标在训练过程中的曲线图吗？

**Comment by huangjy-pku** [comment]
给个邮箱？我发你

**Comment by xjj1999** [comment]
感谢！421559787@qq.com
