### ISSUE TITLE
Where can I find the cliport dataset used in the experiments?

### ISSUE THREAD

**Issue by aabdelreheem55** [embodied-generalist/embodied-generalist#39]
Hi Authors, thank you very much for your great work! I have a question where I can find the dataset for the LeoCLIPort experiments. I have downloaded the provided annotations.zip file but it is not there.

**Comment by huangjy-pku** [comment]
We have released a few data examples of EAI tasks. See the EAI part in [Task and data](https://github.com/embodied-generalist/embodied-generalist?tab=readme-ov-file#task-and-data).
