### ISSUE TITLE
Some questions when running inference

### ISSUE THREAD

**Issue by Txuanwiw** [embodied-generalist/embodied-generalist#4]
您好，感谢您的开源内容。
我在跑推理的时候，在这一步——Build PointcloudBackbone: PointNetPP频繁报错
Error executing job with overrides: ['num_gpu=1', 'note=tuning_noact']
代码问题似乎是来源于pointnetpp.yaml文件中的路径设置
理论上该文件中的path：TBD项应该是pointnetpp的pth文件吧，但是我在完成setup install和测试后没有在相关的文件夹中找到合适的pth文件
请问我的操作哪里有问题呢

**Comment by huangjy-pku** [comment]
You should manually download a checkpoint and then specify the path. See [model weights](https://github.com/embodied-generalist/embodied-generalist?tab=readme-ov-file#model-weights).

**Comment by Txuanwiw** [comment]
不好意思，我疏忽了这点。
感谢您的回答

**Comment by Txuanwiw** [comment]
感谢您的帮助，我已经完成了推理过程，但是推理结果中的response输出全部是乱码
我测试了3rscan和scannet的多个scene，并试着更改了instruction，但是仍然没有得到看起来正常的结果

**Comment by huangjy-pku** [comment]
Can you provide more specific details so that I can reproduce your results?

**Comment by Txuanwiw** [comment]
一切内容都是按照您提供的README文档设置的，我使用的llm是vicnua7b，vision3d是pointnetpp
在设置了所需对应的文件路径后，我将inference.sh中的pretrained_ckpt_path设置为tuning_noact.pth
随后使用bash inference.sh开始推理，监测文档显示模型build、load、freeze全部正常
成功从tuning_noact.pth加载模型后，得到如下推理结果：
[2024-04-11 16:03:32,523][__main__][INFO] - {'source': '3rscan', 'scene_id': '0ad2d3a1-79e2-2212-9b99-a96495d9f7fe', 'situation': '', 'instruction': 'Describe this scene.', 'response': '~~~'}
其中，最后省略的~~~部分全部是乱码，我尝试在inference.py进行json写入时控制参数ensure_ascii=False，但并无作用
另外，我更换了default.yaml中的probe: source、scene_id、instruction进行测试，但都没有帮助
如果您需要的话，我可以为您提供推理结果的probe文件夹，其中包含了监测日志和推理保存的pth

**Comment by huangjy-pku** [comment]
I just instructed the model to "Describe this scene" for `3rscan:0ad2d3a1-79e2-2212-9b99-a96495d9f7fe`. The response is reasonable, which begins with "In this bathroom scene, there is...".

Can you provide your logs (INFO)?

**Comment by Txuanwiw** [comment]
[inference.log](https://github.com/embodied-generalist/embodied-generalist/files/14945822/inference.log)
Here is the log with the same scene and source

**Comment by huangjy-pku** [comment]
I suspect the reason is that you have not loaded `Vicuna-7B` properly. The name `LlamaToken` is weird and there is no log saying `Loading checkpoint shards` which should appear when loading `Vicuna` model. What files are there in your `LlamaToken` folder and where are they from?

**Comment by Txuanwiw** [comment]
The folder "LlamaToken" is used to save the vicuna7b from HuggingFace, because I have to search and download it manually due to the "ConnectionError, port=443".
And the files I obtained are all from "https://huggingface.co/lmsys/vicuna-7b-v1.5"

**Comment by huangjy-pku** [comment]
Weights mismatch. We use Vicuna weights of version v1.1 (see [Model weights](https://github.com/embodied-generalist/embodied-generalist#model-weights)).

**Comment by Txuanwiw** [comment]
The files you posted on HuggingFace seem to have a slight difference from "lmsys/vicuna-7b-v1.1"
I'm downloading the files you provided, but I still wanna ask : Can both of them be used normally?

**Comment by huangjy-pku** [comment]
We have not checked whether our `vicuna-7b-v1.1` is identical to `lmsys`. We manually applied the delta weights (provided by `lmsys`) to `LLaMA` weights to derive the `vicuna-7b-v1.1` weights. I am not sure whether this could lead to the difference. BTW, can you show where the slight difference comes from?

**Comment by Txuanwiw** [comment]
I haven't tried using lmsys in the experiment yet. But when downloading the files you provided, the difference in file size caught my attention. 
The file "config.json", I opened both two files and found the settings for parameters such as "bos_token_id"、“eos_token_id”、"pad_token_id" and "transformers_version" were different. That's may be the SLIGHT difference I mentioned.
I don't have time to explore the effects of these parameters. If the adjustments are to adapt to this project, then I think I have no problem for now. Thanks a lot.

**Comment by yitianlian** [comment]
> 感谢您的帮助，我已经完成了推理过程，但是推理结果中的response输出全部是乱码 我测试了3rscan和scannet的多个scene，并试着更改了instruction，但是仍然没有得到看起来正常的结果

hi，我能否询问一下您的环境配置是cuda 12+的版本吗

**Comment by Txuanwiw** [comment]
> > 感谢您的帮助，我已经完成了推理过程，但是推理结果中的response输出全部是乱码 我测试了3rscan和scannet的多个scene，并试着更改了instruction，但是仍然没有得到看起来正常的结果
> 
> hi，我能否询问一下您的环境配置是cuda 12+的版本吗

yes, cuda 12.0

**Comment by yitianlian** [comment]
> > > 感谢您的帮助，我已经完成了推理过程，但是推理结果中的response输出全部是乱码 我测试了3rscan和scannet的多个scene，并试着更改了instruction，但是仍然没有得到看起来正常的结果
> > 
> > 
> > hi，我能否询问一下您的环境配置是cuda 12+的版本吗
> 
> yes, cuda 12.0

请问一下方便给个环境的txt文件吗，我也是cuda12，但是总是没发跑pointnet这个backbone

**Comment by Txuanwiw** [comment]
> > > > 感谢您的帮助，我已经完成了推理过程，但是推理结果中的response输出全部是乱码 我测试了3rscan和scannet的多个scene，并试着更改了instruction，但是仍然没有得到看起来正常的结果
> > > 
> > > 
> > > hi，我能否询问一下您的环境配置是cuda 12+的版本吗
> > 
> > 
> > yes, cuda 12.0
> 
> 请问一下方便给个环境的txt文件吗，我也是cuda12，但是总是没发跑pointnet这个backbone

[req.txt](https://github.com/embodied-generalist/embodied-generalist/files/15219370/req.txt)

**Comment by Txuanwiw** [comment]
> > > > 感谢您的帮助，我已经完成了推理过程，但是推理结果中的response输出全部是乱码 我测试了3rscan和scannet的多个scene，并试着更改了instruction，但是仍然没有得到看起来正常的结果
> > > 
> > > 
> > > hi，我能否询问一下您的环境配置是cuda 12+的版本吗
> > 
> > 
> > yes, cuda 12.0
> 
> 请问一下方便给个环境的txt文件吗，我也是cuda12，但是总是没发跑pointnet这个backbone

按Readme的教程应该就能跑，我最开始有一些from调用的问题，当时好像是pointnet的文件下载到其它文件夹了，调整过来就正常了

**Comment by yitianlian** [comment]
> > > > > 感谢您的帮助，我已经完成了推理过程，但是推理结果中的response输出全部是乱码 我测试了3rscan和scannet的多个scene，并试着更改了instruction，但是仍然没有得到看起来正常的结果
> > > > 
> > > > 
> > > > hi，我能否询问一下您的环境配置是cuda 12+的版本吗
> > > 
> > > 
> > > yes, cuda 12.0
> > 
> > 
> > 请问一下方便给个环境的txt文件吗，我也是cuda12，但是总是没发跑pointnet这个backbone
> 
> [req.txt](https://github.com/embodied-generalist/embodied-generalist/files/15219370/req.txt)

你这个环境配置文件是不是少了一点包

**Comment by yitianlian** [comment]
![image](https://github.com/embodied-generalist/embodied-generalist/assets/91449279/35068ea1-bda6-49c1-9f79-19e7d5005b1d)
When I want to install pointnetpp, this error accur

**Comment by Txuanwiw** [comment]
> ![image](https://private-user-images.githubusercontent.com/91449279/328182080-35068ea1-bda6-49c1-9f79-19e7d5005b1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDU2OTUsIm5iZiI6MTcxNTA0NTM5NSwicGF0aCI6Ii85MTQ0OTI3OS8zMjgxODIwODAtMzUwNjhlYTEtYmRhNi00OWMxLTlmNzktMTllN2Q1MDA1YjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAxMjk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYzZkZDViMGViODExNzQ2YmIxMDZhMzIzYTYxZDk4MjI3YjVkZTVjN2Q0MWMzN2M0ZGFiOWMzN2VjNGEzNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AHF8Gn560D10TmtiCBAc1R7ACTQ82h280qa-ljAvdTk) When I want to install pointnetpp, this error accur

i can't understand why your cuda cannot be backward compatible. Perhaps you can check to see if there are other versions that are causing this problem.

**Comment by huangjy-pku** [comment]
> ![image](https://private-user-images.githubusercontent.com/91449279/328182080-35068ea1-bda6-49c1-9f79-19e7d5005b1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODIxNzEsIm5iZiI6MTcxNTA4MTg3MSwicGF0aCI6Ii85MTQ0OTI3OS8zMjgxODIwODAtMzUwNjhlYTEtYmRhNi00OWMxLTlmNzktMTllN2Q1MDA1YjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDExMzc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MjQ1ZWFkOGEzZDVjN2M2OTI5ZWNkYTQ4NGI2YjBkMTUxMDE3ODM0NGZlMDJlNTZjNTQ3ZTJiODE5YzczMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WXVPrLqX91nZyOZonZpqRH_vlULjogstkYyVVc0VvsY) When I want to install pointnetpp, this error accur

Maybe you can install pytorch at other versions that support cuda 12. For example, maybe try this:
```
conda install pytorch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 pytorch-cuda=12.1 -c pytorch -c nvidia
```

**Comment by yitianlian** [comment]
> > ![image](https://private-user-images.githubusercontent.com/91449279/328182080-35068ea1-bda6-49c1-9f79-19e7d5005b1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODIxNzEsIm5iZiI6MTcxNTA4MTg3MSwicGF0aCI6Ii85MTQ0OTI3OS8zMjgxODIwODAtMzUwNjhlYTEtYmRhNi00OWMxLTlmNzktMTllN2Q1MDA1YjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDExMzc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MjQ1ZWFkOGEzZDVjN2M2OTI5ZWNkYTQ4NGI2YjBkMTUxMDE3ODM0NGZlMDJlNTZjNTQ3ZTJiODE5YzczMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WXVPrLqX91nZyOZonZpqRH_vlULjogstkYyVVc0VvsY) When I want to install pointnetpp, this error accur
> 
> Maybe you can install pytorch at other versions that support cuda 12. For example, maybe try this:
> 
> ```
> conda install pytorch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 pytorch-cuda=12.1 -c pytorch -c nvidia
> ```

I successfully install pointnet++, but I cant import it:
```bash
Using /home/yiyangai/miniconda3/envs/chengxing_leo_try/lib/python3.9/site-packages
Finished processing dependencies for pointnet2==3.0.0
```
this error appears:
```bash
(chengxing_leo_try) (base) yiyangai@maxwell:~/Projects/chengxingxie/embodied-generalist$ python -c 'from model.pointnetpp.pointnetpp import PointNetPP'
Traceback (most recent call last):
  File "/home/yiyangai/Projects/chengxingxie/embodied-generalist/model/pointnetpp/pointnet2_utils.py", line 23, in <module>
    import pointnet2._ext as _ext
ImportError: /home/yiyangai/miniconda3/envs/chengxing_leo_try/lib/python3.9/site-packages/pointnet2-3.0.0-py3.9-linux-x86_64.egg/pointnet2/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1017SymbolicShapeMeta18init_is_contiguousEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yiyangai/Projects/chengxingxie/embodied-generalist/model/__init__.py", line 2, in <module>
    from .vision3d import OSE3D
  File "/home/yiyangai/Projects/chengxingxie/embodied-generalist/model/vision3d.py", line 7, in <module>
    from model.pcd_backbone import PointcloudBackbone
  File "/home/yiyangai/Projects/chengxingxie/embodied-generalist/model/pcd_backbone.py", line 9, in <module>
    from model.pointnetpp.pointnetpp import PointNetPP
  File "/home/yiyangai/Projects/chengxingxie/embodied-generalist/model/pointnetpp/pointnetpp.py", line 3, in <module>
    from model.pointnetpp.pointnet2_modules import PointnetSAModule
  File "/home/yiyangai/Projects/chengxingxie/embodied-generalist/model/pointnetpp/pointnet2_modules.py", line 21, in <module>
    import pointnet2_utils
  File "/home/yiyangai/Projects/chengxingxie/embodied-generalist/model/pointnetpp/pointnet2_utils.py", line 26, in <module>
    raise ImportError(
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst
```

**Comment by yitianlian** [comment]
I finally found out how to solve the import error, I hope you can include this in the readme part:
You should install pointnet++ from the original repo:
```bash
git clone https://github.com/erikwijmans/Pointnet2_PyTorch.git
cd Pointnet2_PyTorch
pip install pointnet2_ops_lib/.
```
If the last step trigger another error like:
```bash
      nvcc fatal   : Unsupported gpu architecture 'compute_37'
      error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pointnet2_ops
  Running setup.py clean for pointnet2_ops
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zi8vpr6o/pointnet2-ops_03476694dfae46a19d022fa9ff7ccadf/pointnet2_ops_lib/setup.py", line 17, in <module>
          exec(open(osp.join("pointnet2_ops", "_version.py")).read())
      FileNotFoundError: [Errno 2] No such file or directory: 'pointnet2_ops/_version.py'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pointnet2_ops
Failed to build pointnet2_ops
ERROR: Could not build wheels for pointnet2_ops, which is required to install pyproject.toml-based projects
```
you should open `setup.py` file and change:
```python
# os.environ["TORCH_CUDA_ARCH_LIST"] = "3.7+PTX;5.0;6.0;6.1;6.2;7.0;7.5"
os.environ["TORCH_CUDA_ARCH_LIST"] = "5.0;6.0;6.1;6.2;7.0;7.5"
```
Then you can run `pip install pointnet2_ops_lib/.`.
After that, go back to the `model/pointnetpp/pointnet2_utils.py`
change the _ext line to `import pointnet2_ops._ext as _ext`, then you can run the command to check if you can import pointnetpp:
```python
python -c 'from model.pointnetpp.pointnetpp import PointNetPP'
```

**Comment by huangjy-pku** [comment]
I don't know what happens to your environment. But there is nothing wrong with my environment. I simply create a new conda env and follow the `readme` to install `pointnetpp`. It still works and I can import `pointnetpp`.
