### ISSUE TITLE
Can not reproduce the result using training code

### ISSUE THREAD

**Issue by CurryYuan** [embodied-generalist/embodied-generalist#40]
Hi @huangjy-pku ,

Thanks for sharing the code. 

I train the mode with the pertaining [train_align_lora.sh](https://github.com/embodied-generalist/embodied-generalist/blob/main/scripts/train_align_lora.sh) and fine-tuning [train_tuning_noact.sh](https://github.com/embodied-generalist/embodied-generalist/blob/main/scripts/train_tuning_noact.sh) scripts, the results are much lower than the released weights. Especially, the CIDEr score on Scan2Cap is 65.7 (72.4), ScanQA 88.2 (101.4), SQA3D EM 46 (50). Could there be differences between the provided scripts and the settings you used?

**Comment by huangjy-pku** [comment]
Can you share your log file?
