### ISSUE TITLE
Question about ScanQA dataset

### ISSUE THREAD

**Issue by CurryYuan** [embodied-generalist/embodied-generalist#41]
Hi @huangjy-pku ,

Thanks for sharing the code.

I have a question about the ScanQA dataset. In [dataloader](https://github.com/embodied-generalist/embodied-generalist/blob/dd19414cb2a68c9e43b6441c647ce88678a2d34d/data/datasets.py#L775), the object_ids are used to select objects relevant to the question. However, this information should not be used during the test.

**Comment by huangjy-pku** [comment]
The explanation for this operation is that we need to guarantee the relevant objects are not truncated due to the setting of `max_obj_len`.
