### ISSUE TITLE
Demo results are different

### ISSUE THREAD

**Issue by jkstyle2** [embodied-generalist/embodied-generalist#42]
Hello,
I'm working on your project with demo.
However, I found the results from each demo were different.
The result from your [Huggingface interactive demo](https://huggingface.co/spaces/embodied-generalist/LEO-Demo) is : 
![image](https://github.com/user-attachments/assets/3355bc03-f5b5-42e9-be3f-745bc8319f2f)

And using the [pretrained ckpts](https://huggingface.co/datasets/huangjy-pku/LEO_data/tree/main) (align.pth) you shared is :
![image](https://github.com/user-attachments/assets/d0549aa2-38ea-4dea-b8ae-af68c5369313)

It seems the ckpt you're using for the demo is much better than you shared.
Can you explain why are they different and if you can, can you please share the ckpt you're using for the interactive demo?

**Comment by jkstyle2** [comment]
@huangjy-pku 
I want to test a another scene data, by exporting into the demo. 
As the data format used for demo is in .glb. I just directly converted a data from original scannet/3rscan file in ply format into .glb by trimesh.export("output.glb"), but the result seems quite darker than original file. 
![image](https://github.com/user-attachments/assets/79bfa480-b807-4144-955a-fc237f4046da)

Can you please share code how to make a .glb file for the demo?

**Comment by huangjy-pku** [comment]
Sorry for my late reply.
1. The checkpoint for the HF demo is different from the released checkpoint. The released checkpoint refers to the model weights simply following the training scheme as mentioned in our paper. The checkpoint for the HF demo is derived by finetuning the released checkpoint on a re-balanced dataset.
2. Our `.glb` file is exported via `Blender`. @Germany321

**Comment by huangjy-pku** [comment]
To clarify, the `.glb` file is just used for visualization. The input to the demo model is still point cloud. To achieve faster inference speed, we pre-extracted object tokens and loaded them during inference in the demo.

**Comment by Germany321** [comment]
> @huangjy-pku I want to test a another scene data, by exporting into the demo. As the data format used for demo is in .glb. I just directly converted a data from original scannet/3rscan file in ply format into .glb by trimesh.export("output.glb"), but the result seems quite darker than original file. ![image](https://private-user-images.githubusercontent.com/34189274/356984301-79bfa480-b807-4144-955a-fc237f4046da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTQ5MjMsIm5iZiI6MTcyMzYxNDYyMywicGF0aCI6Ii8zNDE4OTI3NC8zNTY5ODQzMDEtNzliZmE0ODAtYjgwNy00MTQ0LTk1NWEtZmMyMzdmNDA0NmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA1NTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NDM3NzdiYTA0YWE4MDhjOGI5ZjEwMGQyZGNmOWQ5MmEwY2EyYjQzMTliMGU5YzIzZWYzNmNhNjY4NmQ4ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8dpeKxJzWc8JqbG3BjYJjdUvX8kBmgTkC-37DaWx_6Q)
> 
> Can you please share code how to make a .glb file for the demo?

The glb files in the live demo was exported by Blender. The settings in Blender may differ from the default settings of trimesh, such as illumination, material reflectivity and so on, which may lead to different rendering results. Besides, the glb files in the live demo is different from the ones in the inference workflow.

**Comment by jkstyle2** [comment]
@huangjy-pku @Germany321 It's now clear. Thanks for sharing the information!
One more question regarding your mention 

> The checkpoint for the HF demo is derived by finetuning the released checkpoint on a re-balanced dataset.

How did you finetune and what is the re-balanced dataset? It seems the HF weight much better than the released weight.

**Comment by huangjy-pku** [comment]
Sorry for my ambiguous reply. To be brief, the checkpoint for the hf demo is trained on a cleaner dataset without biased responses such as Scan2Cap object captions.

**Comment by jkstyle2** [comment]
Can you elaborate what 'cleaner dataset' means? 
I'm curious about your opinion why you think that the dataset like Scan2cap is biased. 
Do you mean the dataset without Scan2Cap is a more balanced dataset so that the model can generate more natural response?

**Comment by huangjy-pku** [comment]
Cleaner means less harmful bias. You can go through the captions, which I personally think are not so natural. Such captions  would possibly make the model respond like that.
