### ISSUE TITLE
Integrating Mask3D into LEO

### ISSUE THREAD

**Issue by jkstyle2** [embodied-generalist/embodied-generalist#43]
Referring to the previous [issue](https://github.com/embodied-generalist/embodied-generalist/issues/16), can you share the personal communication regarding 3D object proposals from Mask3D?
I'd like to integrate the 3D proposal part into LEO and see if it works for a custom scene dataset.
Can you share how you utilized the [Mask3D](https://github.com/JonasSchult/Mask3D) project? 
Also, do you think the 3D proposal part can be substitued to other 3D object detectors like [VoteNet](https://github.com/facebookresearch/votenet)?

**Comment by huangjy-pku** [comment]
For convenience, it would be better for us to contact through WeChat (18770881992).
