### ISSUE TITLE
关于scan2cap任务的cider指标复现问题

### ISSUE THREAD

**Issue by syqisme** [embodied-generalist/embodied-generalist#44]
你好，首先感谢您的出色工作，它给了我很多启发。我目前正在尝试复现您论文中的结果，针对tuning_noact任务。我在加载了第一阶段的训练模型后，进入第二阶段进行复现。但是我在scan2cap任务的cider评估指标上遇到了问题，我的最好结果大约在55左右，而始终无法达到论文中报告的72.4。

具体来说，在训练过程中，我使用了两块80GB的A800 GPU，并且保持了所有参数与默认设置一致。此外，我尝试直接加载您提供的sft_noact.pth权重文件，跳过训练阶段，只进行验证步骤(val_step)，但是发现在scan2cap任务上的cider指标依旧无法达到论文中的结果。

请问您能帮助我诊断可能的问题吗？或者提供一些调整建议吗？非常感谢！

**Comment by huangjy-pku** [comment]
可以提供跑的指令和log文件吗

**Comment by syqisme** [comment]
感谢作者的回复，下面上传的leo_log.txt是我的运行log文件，由于我是提交到集群上使用的，集群无法连接网络，因此我提前下载好了sentence_transformer，vicuna，convnext_base.clip_laion2b并直接加载。同时加载了第一阶段训练好的，作者在github上提供的模型权重文件，数据集方面，我下载了readme中提到的除了cap3d之外的数据集。跑的指令我写成了bash文件，名为myrun.sh,其内容为：#!/bin/bash

# 激活虚拟环境
source /root/anaconda3/bin/activate leo

# 切换到工作目录
cd /embodied-generalist

# 获取当前时间
now=$(date +"%Y%m%d_%H%M%S")

# 设置任务名称
job='leo'

# 创建日志目录
mkdir -p log

python launch.py --name leo_tuning \
                 --mode accelerate \
                 --qos lv0b \
                 --mem_per_gpu 100 \
                 --time 48 \
                 --config /embodied-generalist/configs/default.yaml \
                 --port 2050 \
                 --gpu_per_node 2 \
                 --num_nodes 1 \
                 --partition HGX \
                 task=tuning_noact \
                 note=tuning_noact \
                 pretrained_ckpt_path="/embodied-generalist/preparation/weight/align.pth" \
[leo_log.txt](https://github.com/user-attachments/files/16861713/leo_log.txt)

**Comment by huangjy-pku** [comment]
log似乎没什么问题。可以再确认下Vicuna的版本吗？以及，可以load下第二阶段我们releases的第二阶段训练完的checkpoints做下evaluation，来确定问题是出在training还是evaluation (如果有问题的话)？

**Comment by syqisme** [comment]
你好，我检查了vicuna的版本，重新上传了一次，按照readme中vicuna部分点开后的版本上传的
下载的链接是：https://huggingface.co/huangjy-pku/vicuna-7b/tree/main
除此之外，我重新按照readme的配置环境部分的说明配置了环境。
为了防止之前我改动哪里出错，我从一个新的项目重新配置开始进行实验，加载了预训练的第二阶段的模型sft_noact.pth,注释掉tran_step,只进行val_step，但是发现目前效果还是不好。这是我的日志
[leo_val.txt](https://github.com/user-attachments/files/16973419/leo_val.txt)

**Comment by syqisme** [comment]
作者你好，由于我尝试训练第二阶段，因此我在训练过程中没有使用cap3d数据集，因此我把tuning_noact.yaml关于这个数据集这部分注释掉了
<img width="410" alt="image" src="https://github.com/user-attachments/assets/27bafec7-026b-43f3-97cc-d5c01dd31feb">

**Comment by huangjy-pku** [comment]
我刚才又eval了一遍`sft_noact.pth`这个checkpoint，结果是正常的，比你要高不少。这是我跑的指令和结果:
```bash
python launch.py --name eval \
                 --qos lv0b \
                 --mem_per_gpu 100 \
                 --time 10 \
                 --config configs/default.yaml \
                 --port 2080 \
                 --gpu_per_node 2 \
                 --num_nodes 1 \
                 --partition DGX \
                 mode=eval \
                 task=test_scannet \
                 note=test_scannet_240913 \
                 pretrained_ckpt_path=sft_noact.pth
```
[eval_sft_noact.log](https://github.com/user-attachments/files/16993349/eval_sft_noact.log)

提醒一下，`sft_noact.pth`应该被重命名成`pytorch_model.bin`然后放到名为`sft_noact.pth`的文件夹下。然后`pretrained_ckpt_path`要设为这个文件夹的路径(`sft_noact.pth`)。对于你的问题，有三种可能: model的input data有问题; model的weights有问题; evaluator有问题。我觉得1和3的概率很低，可能还是2。如果实在不行，你可以把model load完ckpt开始eval之前的weights都存下来，再和我的对比一下。
