### ISSUE TITLE
关于完整的机器人导航和操作数据集的问题

### ISSUE THREAD

**Issue by unira-zwj** [embodied-generalist/embodied-generalist#46]
作者您好，

很高兴您能分析如此精彩的工作，我们在尝试复线机器人操作和导航部分的能力，请问后续什么时候会发布完整的这部分数据呢？

非常感谢

**Comment by huangjy-pku** [comment]
导航数据已上传到了[这里](https://huggingface.co/datasets/zhangyuejoslin/LEO_Data)，机器人操作数据太大了，有600多G，还没上传。

**Comment by unira-zwj** [comment]
> 导航数据已上传到了[这里](https://huggingface.co/datasets/zhangyuejoslin/LEO_Data)，机器人操作数据太大了，有600多G，还没上传。

好的，感谢感谢。600多g确实太大了，您看看啥时候网络快了方便了再传吧，不耽误您工作。

再次感谢您的工作分享

**Comment by huangjy-pku** [comment]
感谢理解，如果确有需要可以私戳我传你一部分数据。

**Comment by unira-zwj** [comment]
谢谢您，为了不麻烦您，我使用cliport的仓库生成了一些数据可以用。

但是我遇到了一些问题，我发现直接生成的是斜向下的三个视角的图像，我想请问您方便分享一下生成您用的垂直向下的图像的代码吗？
感谢感谢，这样就不用上传下载大量的数据了。

Jiangyong Huang ***@***.***> 于2024年10月14日周一 13:29写道：

**Comment by unira-zwj** [comment]
您好，我已经解决这个问题啦， 再次感谢您～

以后希望可以和您多多交流具身方向的

Weijie Zhou ***@***.***> 于2024年10月14日周一 17:27写道：

**Comment by BlackTea-c** [comment]
太强了哥
