### ISSUE TITLE
Link of the training data is 404

### ISSUE THREAD

**Issue by xwjim** [embodied-generalist/embodied-generalist#49]
Thanks for your great work. The link to the training data is 404. Could you please provide a new link of the entire training data? Thanks a lot.

**Comment by huangjy-pku** [comment]
I just check the link and it is ok. Could you show the specific link that is 404 to you?

**Comment by xwjim** [comment]
> I just check the link and it is ok. Could you show the specific link that is 404 to you?

![image](https://github.com/user-attachments/assets/76da4051-785b-441d-a600-15475b3f43cd)
Yes. The error is shown as above.

**Comment by huangjy-pku** [comment]
Please check the latest README. We have changed the URL for data.

**Comment by jimboH** [comment]
The link showed 404 to me as well. Could you please update the new URL~ Thanks!

**Comment by huangjy-pku** [comment]
The updated URL in [README](https://github.com/embodied-generalist/embodied-generalist?tab=readme-ov-file#task-and-data) is [https://huggingface.co/datasets/huangjy-pku/LEO_data/tree/main](https://huggingface.co/datasets/huangjy-pku/LEO_data/tree/main).
