### ISSUE TITLE
About training time&memory

### ISSUE THREAD

**Issue by hanxunyu** [embodied-generalist/embodied-generalist#50]
Hi, thanks for your great work.
May I ask what the training time and memory usage are when using the 7B parameter LLM?
Looking forward to your reply~

**Comment by hanxunyu** [comment]
Hi, could you please explain it to me? Thanks a lot.

**Comment by huangjy-pku** [comment]
In our default setting, it takes about 8 hours and 2 hours per align epoch and sft epoch (4 A100/A800 GPU), respectively. Memory usage depends on the tasks (sequence length). For tasks with short input and short output (e.g., QA), the whole training takes about 40G GPU memory. When involving tasks with long input and long output (e.g., dialogue and planning), the memory usage increases to 80G.

If you mean using the solely 7B LLM for inference, a 24G GPU like RTX 3090 is adequate.
