### ISSUE TITLE
EAI task display

### ISSUE THREAD

**Issue by zhangerdi0106** [embodied-generalist/embodied-generalist#53]
I want to visualize the robot's action grasping tasks, and I've seen demo videos, but I couldn't find the related code in the repository

**Comment by huangjy-pku** [comment]
Our manipulation task is based on [CLIPort](https://github.com/cliport/cliport). We adapt their code for our use, including data generation, evaluation, and demo recording.

**Comment by zhangerdi0106** [comment]
Thank you for your reply. I have just started learning about embodied intelligence and am focusing on the robotic manipulation aspect. I would like to receive your team's modified code or ideas regarding Cliport

**Comment by zhangerdi0106** [comment]
你好，我正在复现您的论文，有问题想请教，我看开源代码介绍里没有提到微调以后模型测试的部分，我该如何使用lora微调之后的大语言模型呢



---- Replied Message ----
| From | Jiangyong ***@***.***> |
| Date | 12/04/2024 12:34 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [embodied-generalist/embodied-generalist] EAI task display (Issue #53) |

Our manipulation task is based on CLIPort. We adapt their code for our use, including data generation, evaluation, and demo recording.

**Comment by zhangerdi0106** [comment]
你好，我正在复现您的LEO项目，有问题想请教，我看开源代码介绍里没有提到微调以后模型测试的部分，我该如何使用lora微调之后的大语言模型呢



---- Replied Message ----
| From | Jiangyong ***@***.***> |
| Date | 12/04/2024 12:34 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [embodied-generalist/embodied-generalist] EAI task display (Issue #53) |

Our manipulation task is based on CLIPort. We adapt their code for our use, including data generation, evaluation, and demo recording.

**Comment by huangjy-pku** [comment]
> 你好，我正在复现您的LEO项目，有问题想请教，我看开源代码介绍里没有提到微调以后模型测试的部分，我该如何使用lora微调之后的大语言模型呢
> […](#)
> ---- Replied Message ---- | From | Jiangyong ***@***.***> | | Date | 12/04/2024 12:34 | | To | ***@***.***> | | Cc | ***@***.***>***@***.***> | | Subject | Re: [embodied-generalist/embodied-generalist] EAI task display (Issue #53) | Our manipulation task is based on CLIPort. We adapt their code for our use, including data generation, evaluation, and demo recording. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Readme的[Running](https://github.com/embodied-generalist/embodied-generalist#running)部分有关于inference的介绍，提供输入的场景和语言指令就行。

**Comment by zhangerdi0106** [comment]
懂了，非常感谢



---- 回复的原邮件 ----
| 发件人 | Jiangyong ***@***.***> |
| 日期 | 2024年12月05日 11:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [embodied-generalist/embodied-generalist] EAI task display (Issue #53) |

你好，我正在复现您的LEO项目，有问题想请教，我看开源代码介绍里没有提到微调以后模型测试的部分，我该如何使用lora微调之后的大语言模型呢
…
---- Replied Message ---- | From | Jiangyong @.> | | Date | 12/04/2024 12:34 | | To | @.> | | Cc | @.>@.> | | Subject | Re: [embodied-generalist/embodied-generalist] EAI task display (Issue #53) | Our manipulation task is based on CLIPort. We adapt their code for our use, including data generation, evaluation, and demo recording. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

Readme的Running部分有关于inference的介绍，提供输入的场景和语言指令就行。

**Comment by Xiaoyao-Li** [comment]
> 你好，我正在复现您的LEO项目，有问题想请教，我看开源代码介绍里没有提到微调以后模型测试的部分，我该如何使用lora微调之后的大语言模型呢
> […](#)
> ---- Replied Message ---- | From | Jiangyong ***@***.***> | | Date | 12/04/2024 12:34 | | To | ***@***.***> | | Cc | ***@***.***>***@***.***> | | Subject | Re: [embodied-generalist/embodied-generalist] EAI task display (Issue #53) | Our manipulation task is based on CLIPort. We adapt their code for our use, including data generation, evaluation, and demo recording. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

您好，我们测试的思路是将leo的环境和cliport隔离开，利用socket通讯cliport simulator中的数据和leo给出的action。

**Comment by zhangerdi0106** [comment]
您好，python launch.py --mode python \
                 --run_file inference.py \
                 --config configs/default.yaml \
                 note=tuning_noact \
                 pretrained_ckpt_path=null \文档说明pretrained_ckpt_path是存放pytorch_model.bin的路径，请问pytorch_model.bin权重文件是初始模型微调之后的吗，我需要将sft_noact.pth和初始模型权重文件合并成pytorch_model.bin吗

**Comment by huangjy-pku** [comment]
> 您好，python launch.py --mode python --run_file inference.py --config configs/default.yaml note=tuning_noact pretrained_ckpt_path=null \文档说明pretrained_ckpt_path是存放pytorch_model.bin的路径，请问pytorch_model.bin权重文件是初始模型微调之后的吗，我需要将sft_noact.pth和初始模型权重文件合并成pytorch_model.bin吗

不用合并，直接load就行。

**Comment by zhangerdi0106** [comment]
您好，我修改了leo_trainer文件里的def load(self, path, model_only=False):
        if model_only:
            model_state_dict = torch.load(os.path.join(path, 'sft_noact.pth'))#pytorch_model.bin我改的 sft_noact.pth，运行inference.py输出response为
![image](https://github.com/user-attachments/assets/c77916dd-c0b0-4899-b4a6-0a3ae910904b)
response为乱码，是我加载的微调后权重文件有问题吗

**Comment by huangjy-pku** [comment]
请提供完整的log，另外确保所有的pretrained weights没问题（比如Vicuna-v1.1）

**Comment by zhangerdi0106** [comment]
感谢指导，使用了匹配的Vicuna-v1.1，response正常
