### ISSUE TITLE
[bug] ImportError: cannot import name 'pointnet2_batch_cuda' from partially initialized module 'model.pointnext.cpp.pointnet2_batch' (most likely due to a circular import) (/home/j/v/aigc/embodied-generalist/model/pointnext/cpp/pointnet2_batch/__init__.py)

### ISSUE THREAD

**Issue by 0926yangbo** [embodied-generalist/embodied-generalist#6]
following the guide of README.md, I got the following error when I type: python -c 'from model.pointnetpp.pointnetpp import PointNetPP':

from model.pointnext.pointnext import PointNext
  File "/home/j/v/aigc/embodied-generalist/model/pointnext/pointnext.py", line 11, in <module>
    from model.pointnext.layers import CHANNEL_MAP, create_act, create_convblock1d, create_convblock2d, \
  File "/home/j/v/aigc/embodied-generalist/model/pointnext/layers.py", line 12, in <module>
    from model.pointnext.cpp import pointnet2_cuda
  File "/home/j/v/aigc/embodied-generalist/model/pointnext/cpp/__init__.py", line 6, in <module>
    from .pointnet2_batch import pointnet2_cuda
  File "/home/j/v/aigc/embodied-generalist/model/pointnext/cpp/pointnet2_batch/__init__.py", line 2, in <module>
    from . import pointnet2_batch_cuda as pointnet2_cuda
ImportError: cannot import name 'pointnet2_batch_cuda' from partially initialized module 'model.pointnext.cpp.pointnet2_batch' (most likely due to a circular import) (/home/j/v/aigc/embodied-generalist/model/pointnext/cpp/pointnet2_batch/__init__.py)

**Comment by huangjy-pku** [comment]
The reason may be you have not installed `pointnext` dependency properly. You can check the log. Also, one backup is to comment the lines concerning `pointnext` since it does not relate to the model by default.

**Comment by 0926yangbo** [comment]
> python -c 'from model.pointnetpp.pointnetpp import PointNetPP'
3ks, I comment the lines concerning pointnext, the module can be correctly loaded.

**Comment by huangjy-pku** [comment]
In addition, we provide a [compiled file](https://drive.google.com/file/d/1MkOiy3UKitVFMccePxk3nl-XCJeaxBvR/view?usp=sharing) as a workaround for the installation failure of `PointNext`, which you can download and place at `model/pointnext/cpp/pointnet2_batch/`. With this file prepared, you should be able to import `PointNext` successfully.
