### ISSUE TITLE
3D urban buildings 

### ISSUE THREAD

**Issue by KongFulu** [embodied-generalist/embodied-generalist#8]
Hello, I would like to know how the LEO developed by your team performs in a large-scale scene at the level of 3D urban buildings

**Comment by KongFulu** [comment]
比如说某城市发生了火灾，我想通过大模型来对城市实景三维模型进行分割分析，并按照需求重构三维场景（目的是为了消除哪些与我当前分析事件不相关的三维物体）

**Comment by KongFulu** [comment]
For example, if there is a fire in a city, I want to use a large model to segment and analyze the 3D model of the city, and reconstruct the 3D scene according to my needs (the purpose is to eliminate 3D objects that are not related to the current analysis event

**Comment by huangjy-pku** [comment]
We mainly focus on indoor 3D scenes. Urban outdoor scenes are out of the scope of this work. And 3D scene segmentation or reconstruction is also out of our scope.
