### ISSUE TITLE
Huggingface interactive demo failed

### ISSUE THREAD

**Issue by jkstyle2** [embodied-generalist/embodied-generalist#9]
Hello,
I tried Huggingface interactive demo last week, but not it got failed as below. Is it under the construction ?
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/11a8b7b5-0baa-4cc0-b558-b8b8914abdc9)

**Comment by jkstyle2** [comment]
Thanks for your help.

I found it interesting for the ability of your model to describe the entire scene.
Here are the results I tested with the example prompt "Descrbie the scene".
It seems somewhat correctly matched, but also resulted a few wrong captions.
Is there any possibility to be imporved on the scene captioning task?
I also wonder if there are publicly available annotations for the scene captioning tasks.

![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/b4306da6-ac8f-4e16-b95c-778940eab27c)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/7bba29a8-af6c-4ff3-b675-d11e9911c72c)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/e10a2f02-7c25-4e0f-8024-80663ea8f69b)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/1243c015-5a54-44bc-b32a-474dda29e8e3)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/8447f589-a829-450a-b8c8-760b57ef44ef)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/ca3ce9b7-77f5-4523-a80d-82cb9ed2b736)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/e325f278-33eb-48d4-85a3-ed5dfa50d98b)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/ca38b69e-ea7e-46d6-9198-11e40ba68c9b)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/4368ac87-6c9b-425e-b574-69960dc711e7)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/32ca4c50-b6a9-4497-b09d-e58e44dd8f5a)

**Comment by huangjy-pku** [comment]
You can finetune the model solely on the scene captioning task.
